version: '3'
services:
  nginx:
    image: nginx:1.27.0
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi-app

  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./logs/:/usr/src/logs/
    environment:
      APP_ENV: $APP_ENV
      SECRET_KEY: $SECRET_KEY
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
